<?php
/**
 * @file
 * Code for the FT: Site Administration feature.
 */

use davidlukac\drupal_oop\Theme;

include_once 'ft_site_administration.features.inc';

/**
 * Implements hook_post_features_enable_feature().
 *
 * Enable `Adminimal` theme when enabling this feature.
 *
 * @inheritdoc
 */
function ft_site_administration_post_features_enable_feature($component) {
  // When we get to enabling the Strongarm variables for this Feature,
  // make sure the theme is enabled and it's settings are reverted afterwards,
  // so they are applied correctly.
  if ($component == 'variable') {
    // Load our dependencies first.
    module_load_include('php', 'drupal_oop', 'vendor/autoload');

    $theme_name = 'adminimal';
    $admin_theme = new Theme($theme_name);
    $admin_theme->enable();
    features_revert(array('ft_site_administration' => array($component)));
    watchdog(FTSiteAdministrationModule::getName(), "Attempted to enable the Adminimal theme.", array(), WATCHDOG_INFO);

    if ($admin_theme->checkIfEnabled()) {
      watchdog(FTSiteAdministrationModule::getName(), "Adminimal theme enabled successfully.", array(), WATCHDOG_INFO);
    }
    else {
      watchdog(FTSiteAdministrationModule::getName(), "The Adminimal theme is not present. Requested: '%req'.", array('%req' => $theme_name), WATCHDOG_ERROR);
    }
  }
}
